"""
Dota 2 Hero Aliases and Russian Slang Dictionary
Allows players to quickly search heroes by common nicknames, abbreviations, and Russian names.
"""

HERO_ALIASES = {
    "Anti-Mage": ["ам", "магина", "am", "magina", "antimage"],
    "Axe": ["акс", "топор", "axe"],
    "Bane": ["бейн", "бане", "bane", "atropos"],
    "Bloodseeker": ["бс", "сикер", "бладсикер", "bs", "seeker", "blood"],
    "Crystal Maiden": ["цм", "цмка", "рилай", "cm", "maiden", "rylai"],
    "Drow Ranger": ["тракса", "дровка", "дроу", "drow", "traxex"],
    "Earthshaker": ["шейкер", "ес", "эртшейкер", "es", "shaker"],
    "Juggernaut": ["джаггер", "югик", "юзер", "jugg", "jug", "yurnero"],
    "Mirana": ["мирана", "потма", "кот", "стрела", "potma", "mirana"],
    "Morphling": ["морф", "вода", "morph", "morphling"],
    "Shadow Fiend": ["сф", "невер", "койлы", "sf", "nevermore"],
    "Phantom Lancer": ["пл", "лансер", "иллюзионист", "pl", "lancer"],
    "Puck": ["пак", "шарик", "puck"],
    "Pudge": ["пудж", "мясник", "падж", "рука", "хук", "pudge", "butcher"],
    "Razor": ["разор", "электрик", "razor"],
    "Sand King": ["ск", "скорп", "песок", "sk", "sandking", "crixalis"],
    "Storm Spirit": ["шторм", "панда", "электрик", "storm", "ss"],
    "Sven": ["свен", "синий", "sven", "rogue"],
    "Tiny": ["тини", "камень", "tiny"],
    "Vengeful Spirit": ["венга", "птица", "свап", "vs", "venge", "vengeful"],
    "Windranger": ["вр", "врка", "ветер", "рыжая", "wr", "wind"],
    "Zeus": ["зевс", "бог", "молния", "дед", "zeus", "zuus"],
    "Kunkka": ["кунка", "адмирал", "корабль", "крест", "kunkka", "admiral"],
    "Lina": ["лина", "сестра", "огонь", "lina"],
    "Lion": ["лион", "палец", "лягушка", "hex", "lion"],
    "Shadow Shaman": ["шаман", "расту", "змейки", "ss", "shaman", "rhasta"],
    "Slardar": ["селедка", "рыба", "стан", "слырдар", "slardar"],
    "Tidehunter": ["тайд", "арбуз", "рыба", "tide", "hunter"],
    "Witch Doctor": ["вд", "доктор", "бочка", "маледикт", "wd", "witchdoctor"],
    "Lich": ["лич", "чайник", "мороз", "lich", "ethreain"],
    "Riki": ["рики", "крыса", "инвиз", "riki", "sa"],
    "Enigma": ["энигма", "дыра", "блэкхол", "черная дыра", "enigma", "bh"],
    "Tinker": ["тинкер", "ракеты", "робот", "tinker", "boush"],
    "Sniper": ["снайпер", "дед", "карлик", "sniper", "kardel"],
    "Necrophos": ["некр", "дед", "коса", "necro", "necrophos"],
    "Warlock": ["варлок", "голем", "дед", "warlock"],
    "Beastmaster": ["бм", "бист", "кабан", "bm", "beast"],
    "Queen of Pain": ["квопа", "королева", "боль", "qop", "queen"],
    "Venomancer": ["веник", "змея", "яд", "veno", "venomancer"],
    "Faceless Void": ["войд", "купол", "куполмен", "fv", "void"],
    "Wraith King": ["вк", "папич", "леорик", "король", "скелет", "wk", "leoric"],
    "Death Prophet": ["дп", "кробелус", "баньша", "духи", "dp", "krobelus"],
    "Phantom Assassin": ["па", "мортра", "фантомка", "криты", "pa", "mortred"],
    "Pugna": ["пугна", "соска", "варда", "зеленый", "pugna"],
    "Templar Assassin": ["та", "ланая", "темпларка", "щит", "ta", "lanaya"],
    "Viper": ["вайпер", "змея", "плюйка", "viper"],
    "Luna": ["луна", "лунная", "ульта", "luna"],
    "Dragon Knight": ["дк", "рыцарь", "дракон", "dk", "dragon"],
    "Dazzle": ["дазл", "крест", "хил", "розовый", "dazzle"],
    "Clockwerk": ["клок", "крюк", "батарейка", "коги", "clock", "clockwerk"],
    "Leshrac": ["лешрак", "конь", "осел", "ракета", "lesh", "leshrac"],
    "Nature's Prophet": ["фурион", "фура", "пень", "дерево", "телепорт", "np", "furion", "prophet", "natures"],
    "Lifestealer": ["гуля", "найкс", "собака", "гуль", "ls", "naix", "lifestealer"],
    "Dark Seer": ["дс", "сир", "стенка", "голова", "ds", "darkseer"],
    "Clinkz": ["клинкз", "боник", "скелет", "лучник", "clinkz", "bone"],
    "Omniknight": ["омник", "рыцарь", "хил", "молоток", "omni", "omniknight"],
    "Enchantress": ["энча", "коза", "олениха", "хил", "encha", "enchantress"],
    "Huskar": ["хускар", "копья", "прыжок", "огонь", "huskar"],
    "Night Stalker": ["баланар", "нс", "ночь", "крылья", "ns", "balanar"],
    "Broodmother": ["бруда", "паучиха", "паук", "brood", "broodmother"],
    "Bounty Hunter": ["бх", "гондар", "трек", "монеты", "bh", "bounty"],
    "Weaver": ["вивер", "жук", "weaver", "skitskurr"],
    "Jakiro": ["джакиро", "двухголовый", "дракон", "лед и пламень", "jakiro", "thd"],
    "Batrider": ["бэт", "мышь", "лассо", "bat", "batrider"],
    "Chen": ["чен", "крипы", "зоопарк", "chen"],
    "Spectre": ["спектра", "меркуриал", "иллюзии", "spec", "spectre"],
    "Ancient Apparition": ["апарат", "аппарат", "лед", "aa", "ancient"],
    "Doom": ["дум", "люцифер", "печать", "doom", "lucifer"],
    "Ursa": ["урса", "медведь", "мишка", "рошан", "ursa"],
    "Spirit Breaker": ["бара", "бык", "разгон", "sb", "bara", "breaker"],
    "Gyrocopter": ["гиро", "вертолет", "дед", "ракета", "gyro", "gyrocopter"],
    "Alchemist": ["алхимик", "алхим", "монеты", "жадность", "alch", "alchemist"],
    "Invoker": ["инвокер", "вокер", "пианист", "маг", "invo", "invoker", "kael"],
    "Silencer": ["сайленсер", "сало", "тишина", "silencer", "nortrom"],
    "Outworld Destroyer": ["од", "дестр", "астрал", "od", "destroyer"],
    "Lycan": ["ликан", "волк", "псы", "lycan"],
    "Brewmaster": ["панда", "брю", "пиво", "brew", "brewmaster"],
    "Shadow Demon": ["сд", "демон", "иллюзии", "sd", "demon"],
    "Lone Druid": ["лд", "друид", "мишка", "медведь", "ld", "druid"],
    "Chaos Knight": ["чк", "рыцарь хаоса", "конь", "ck", "chaos"],
    "Meepo": ["мипо", "геомансер", "лопата", "клоны", "meepo"],
    "Treant Protector": ["тренч", "дерево", "руфтреллен", "броня", "tree", "treant"],
    "Ogre Magi": ["огр", "маг", "два дебила", "мультикаст", "ogre", "magi"],
    "Undying": ["зомби", "андаинг", "томба", "могила", "undying", "dirge"],
    "Rubick": ["рубик", "вор", "маг", "зеленый", "rubick"],
    "Disruptor": ["дизраптор", "тралл", "круг", "диз", "disr", "disruptor"],
    "Nyx Assassin": ["никс", "жук", "манадрен", "nyx"],
    "Naga Siren": ["нага", "сирена", "сон", "иллюзии", "naga"],
    "Keeper of the Light": ["котл", "дед", "конь", "свет", "маны дай", "kotl", "keeper"],
    "Io": ["висп", "шарик", "светлячок", "wisp", "io"],
    "Visage": ["визаж", "птицы", "горгульи", "visage"],
    "Slark": ["сларк", "рыба", "жаба", "прыжок", "хвост", "slark"],
    "Medusa": ["медуза", "змея", "щит", "стрелы", "dusa", "medusa"],
    "Troll Warlord": ["тролль", "топоры", "ульта", "troll"],
    "Centaur Warrunner": ["кентавр", "конь", "телега", "centaur", "cw"],
    "Magnus": ["магнус", "рп", "рога", "увези", "mag", "magnus"],
    "Timbersaw": ["тимбер", "пила", "дереворуб", "timber", "shredder"],
    "Bristleback": ["бристл", "свинья", "спина", "колючки", "bb", "bristle"],
    "Tusk": ["таск", "морж", "снежок", "кулак", "tusk"],
    "Skywrath Mage": ["скай", "петух", "птица", "ульта", "sky", "skywrath"],
    "Abaddon": ["абаддон", "щит", "ульта", "лорд", "aba", "abaddon"],
    "Elder Titan": ["титан", "чемодан", "дух", "et", "titan"],
    "Legion Commander": ["легионка", "дуэль", "баба", "дуэлянт", "lc", "legion"],
    "Techies": ["течис", "минер", "бомбы", "сапер", "techies"],
    "Ember Spirit": ["эмбер", "панда", "огонь", "ревенанты", "ember"],
    "Earth Spirit": ["земеля", "камень", "панда", "эрт", "earth"],
    "Underlord": ["андерлорд", "питлорд", "портал", "улька", "underlord", "pitlord"],
    "Terrorblade": ["тб", "террор", "свап хп", "метаморфоза", "tb", "terrorblade"],
    "Phoenix": ["феникс", "птица", "яйцо", "огонь", "phoenix"],
    "Oracle": ["оракул", "хил", "ульта", "предсказатель", "oracle"],
    "Winter Wyvern": ["виверна", "зима", "дракон", "ww", "wyvern"],
    "Arc Warden": ["арк", "варден", "клон", "мидас", "zet", "arc", "warden"],
    "Monkey King": ["мк", "обезьяна", "палка", "дерево", "mk", "monkey"],
    "Dark Willow": ["фея", "вилка", "страх", "willow", "dw"],
    "Pangolier": ["панго", "броненосец", "шар", "шпага", "pango", "pangolier"],
    "Grimstroke": ["грим", "кисть", "привязка", "художник", "grim", "grimstroke"],
    "Hoodwink": ["белка", "арбалет", "орех", "hoodwink", "squirrel"],
    "Void Spirit": ["войд спирит", "дух", "инопланетянин", "vs", "voidspirit"],
    "Snapfire": ["бабка", "ящерица", "печенье", "бабуля", "snap", "snapfire"],
    "Mars": ["марс", "арена", "щит", "копье", "mars"],
    "Dawnbreaker": ["валькирия", "молот", "рассвет", "солнце", "db", "dawnbreaker"],
    "Marci": ["марси", "немая", "кулаки", "marci"],
    "Primal Beast": ["бист", "динозавр", "топот", "хватает", "pb", "primal"],
    "Muerta": ["муэрта", "пистолеты", "призрак", "muerta"],
    "Ringmaster": ["рингмастер", "клоун", "циркач", "колесо", "ringmaster"],
    "Kez": ["кез", "птица", "самурай", "мечи", "kez"]
}


def matches_search(query: str, hero_name: str, display_name: str, short_name: str) -> bool:
    """Checks if a search query matches a hero by display name, short name, or aliases."""
    q = query.lower().strip()
    if not q:
        return True

    d_name = display_name.lower()
    s_name = short_name.lower()
    h_name = hero_name.lower()

    if q in d_name or q in s_name or q in h_name:
        return True

    aliases = HERO_ALIASES.get(display_name, [])
    for alias in aliases:
        if q in alias.lower() or alias.lower() in q:
            return True

    return False
